name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Dagger CLI
        run: curl -fsSL https://dl.dagger.io/dagger/install.sh | sudo sh

      - name: Build
        run: dagger -m ./ci call build --source=.

      - name: Lint
        run: dagger -m ./ci call lint --source=.

      - name: Test
        run: dagger -m ./ci call test --source=.
